### ISSUE TITLE
help content

### ISSUE THREAD

**Issue by bjenmonk** [ronan-hello/matomo-dark-theme#1]
help text font color is white. can't view the text. Please change it. Thanks for the theme

**Comment by ronan-hello** [comment]
Hi bjenmonk,
I don't really understand your request, can you take a screenshot of the bug ?

**Comment by ronan-hello** [comment]
> help text font color is white. can't view the text. Please change it. Thanks for the theme

Hi bjenmonk,
I don't really understand your request, can you take a screenshot of the bug ?
