### ISSUE TITLE
Custom reports hightlight makes text unreadable

### ISSUE THREAD

**Issue by hhhuut** [ronan-hello/matomo-dark-theme#10]
Hi there,

I have a problem related to the [Custom Reports](https://plugins.matomo.org/CustomReports) plugin from Matomo.

Initially they look just fine, however after clicking through the reports, they are marked with a white background, which unfortunately hides the names of the reports.
![image](https://user-images.githubusercontent.com/16589718/236408886-f140523e-d3de-4f95-9466-c128ae3edc47.png)

While hovering over the entries to select a custom report to display the background is normal again and the report name is readable.
![image](https://user-images.githubusercontent.com/16589718/236408989-3d54b89a-2e7c-419a-9a7e-d379ba11fa47.png)

**Comment by nadworks** [comment]
Same problem here and the reason why we cannot use the dark theme. Our email reports being clear and accessible is essential. **The intro-text below "Hello" is light-grey on a white background.** 
Seems like a remnant of an expected dark background.
If there's a simple enough solution to fix this on our side, please share.

**Comment by ronan-hello** [comment]
Hi,

I didn't have this plugin, this is the reason why I can't see the problem and fix it.
Maybe you can try to fix this and create a Pull Request ?

**Comment by nadworks** [comment]
It's in other places too. I.e. "forgotten Password" process text is light yellow on white. Any of the standard email notifications from Matomo contain illegible text. You just need to go through your CSS and email styling and apply more fixes to make this dark theme a feasible option.

**Comment by ronan-hello** [comment]
Thank you for opening this issue, 
This have been fixed today in a general batch.
