### ISSUE TITLE
Make Theme Matomo 4 compatible

### ISSUE THREAD

**Issue by Findus23** [ronan-hello/matomo-dark-theme#2]
Hi, hope you are doing well!

Matomo 4 is progressing steadily and it would be great if this theme (and your other theme) was also available for it.

[Migrating the theme](https://matomo.org/blog/2020/08/matomo4-make-your-plugin-compatible-now/) should be pretty simple as there were not many breaking changes and the design didn't change with Matomo 4.

You can find the migration guide here: https://developer.matomo.org/guides/migrate-matomo-3-to-4

It boils down to:
- update your dev environment to 4.x-dev
- update your plugin.json (new major version of the plugin and require `>=4.0.0-b1,<5.0.0-b1`)
- check that everything still works fine
- commit this to a new branch (e.g. `4.x-dev`) and make this branch the default in the github settings
- tag and push a new release to publish it to the marketplace

If you later fix a bug and also want to backport it to the 3.x theme, you can cherry-pick the commit to the old branch, release a new version (lower than the one for 4.x) and publish it and 3.x users should get this update.

If you have questions about anything, just ask me!

**Comment by Findus23** [comment]
I just noticed that you already did this. 

Could you maybe set the 4.x-dev branch as the default branch in the repo settings, so that one immediatly sees the changes.

Thanks.

**Comment by ronan-hello** [comment]
Hi Lukas,

Thank you for this information, I set the 4.x-dev branch as default for 2 themes and the plugin I developed.
I look forward to Matomo 4.0 😊 

Thanks.

**Comment by Findus23** [comment]
Perfect :+1:
