### ISSUE TITLE
Realtime visitors log: Change color of Device icon for dark theme

### ISSUE THREAD

**Issue by foss-** [ronan-hello/matomo-dark-theme#4]
Matomo: 3.14.1
Dark Theme: 1.0.4

**Currently**

Realtime visitor log uses a black icon for device info.

**Expected**

On dark grey background this is barely visible. Icon should use a light color matching color used for user profil icon.

![wrong icon color](https://user-images.githubusercontent.com/5708172/102768796-01351e80-4382-11eb-8d61-ddb2be3ede0b.png)

**Comment by ronan-hello** [comment]
Hi, thank you for submitting your issue !
This have been fixed in this last update

**Comment by foss-** [comment]
Awesome, thanks. And a followup item: https://github.com/ronan-hello/matomo-dark-theme/issues/5
