### ISSUE TITLE
Realtime visitors log: Change color of iOS icon for dark theme

### ISSUE THREAD

**Issue by foss-** [ronan-hello/matomo-dark-theme#5]
Currently black on dark background, Would expect that to be white to match the other icons.

<img width="172" alt="iOS black on dark background" src="https://user-images.githubusercontent.com/5708172/105083928-e98eaa00-5a95-11eb-922c-db93d73e4af6.png">

**Comment by ronan-hello** [comment]
Thank you for opening this issue, it have been fixed since 1.1.4
