### ISSUE TITLE
Dashboard > Visits Summary hard to view with dark theme

### ISSUE THREAD

**Issue by foss-** [ronan-hello/matomo-dark-theme#7]
Matomo: 4.12.3
Dark-Theme: 1.1.7

Visits Summary is hard to read in dark-theme.

![screenshot](https://user-images.githubusercontent.com/5708172/198262009-dab06998-080d-4aca-83ac-f03aac554e6f.png)

**Comment by ronan-hello** [comment]
Hi, I just publish a new version of the theme, tell me if this is fixed ;)

**Comment by foss-** [comment]
Updated to 1.2.0, thanks so much for looking into this. Works fine now.
