### ISSUE TITLE
Low contrast ratio in v1.2.0 (with screens and suggestions)

### ISSUE THREAD

**Issue by dimasites** [ronan-hello/matomo-dark-theme#8]
Hi @ronan-hello and thank for awesome theme!

I just want to suggest for some fixes

### 1. Main link color in all theme
Chrome's accessabiity suggessions alert about low contrast ratio (and in real, visually hard to read some links). I make some design research for find ideal (imho) color 👍 :-) And you might want to use them:
![2023-03-11_23-18-16](https://user-images.githubusercontent.com/5102558/224510669-0d2459d1-fcc9-40cc-a28c-addcea59cab5.png)
Copyable colors: (old) **#3450a3** → **#778fd4** (suggested)

### 2. Icon "View visitor profile" in visitor log and realtime log
![2023-03-11_23-04-13](https://user-images.githubusercontent.com/5102558/224510665-e434f5c4-a19a-4fb8-aa5e-98c38109c22d.png)
its icon color may be set to main link color or just grey (with normal contrast ratio) or white...

### 3. Widget background color fpr "promoWidget"
![2023-03-11_22-45-28](https://user-images.githubusercontent.com/5102558/224510653-5e9afbe0-df37-4a00-afe7-c34a21c3a71d.png)

**Comment by dimasites** [comment]
Update for point 2: in some other widget icons same problem are detected.
Customizable widgets like Visits over time:
 
![image](https://user-images.githubusercontent.com/5102558/224511235-a1863783-38d1-459b-ac98-be6d8e448937.png)

**Comment by dimasites** [comment]
I founded additional wrong color:

![2023-03-12_22-23-19](https://user-images.githubusercontent.com/5102558/224568530-0c28e528-d32b-4e40-b484-789adb560f8d.png)

To fix it, i used this code:
``` css
.siteSelector .custom_select_search .inp{
  color: inherit !important;
}
```

**Comment by ronan-hello** [comment]
Thank you for opening this issue
This is fixed right now !
