### ISSUE TITLE
Incorrect display of visitor's UserId in the "Visitors" - "Real-time" section.

### ISSUE THREAD

**Issue by asedinkin** [ronan-hello/matomo-dark-theme#9]
The problem occurs due to an incorrectly applied CSS rule in the DarkTheme/stylesheets/components/_icon.less file and has the following appearance, in which the name of the user account is displayed in black on a dark background:
![darktheme-bug](https://user-images.githubusercontent.com/148766/235288035-29dce88a-415e-48be-b16c-28d7529fa16e.png)

To solve the problem, you need to replace the code:
`.visits-live-launch-visitor-profile {
  filter: invert(1);
}`
To the following CSS rule:
`.visits-live-launch-visitor-profile .icon-visitor-profile:before {
  filter: invert(1);
}`

**Comment by ronan-hello** [comment]
Thank you for opening this issue, problem fixed today !
Enjoy the update
